spring.application.name=artistas-alura

# URL de conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/artists_db
spring.datasource.username=postgres
spring.datasource.password=12345678

# Driver do banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
# O 'update' faz o Spring criar as tabelas sozinho baseado nas suas @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do IntelliJ o comando SQL que o Spring executou por baixo dos panos
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false